# Generated by Django 5.0.9 on 2024-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_host', models.CharField(max_length=100)),
                ('db_port', models.CharField(max_length=10)),
            ],
        ),
    ]
