# Generated by Django 5.0.9 on 2024-11-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='inventory_c_code_710414_idx',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
